name: Saut en Parachute Paris
favicon: null
layout_spectrum: 1
typography_spectrum: 0.011854069773107767
title: Saut en Parachute Paris
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#224086'
    - '#c7cfe3'
    - '#69a1dc'
    - '#0c0c14'
    - '#5f380f'
  brandStrength: 0.1875
  lightness: 0.625
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
